In [1]:
import sys
import os
from source import plotFunctions
from timeit import default_timer as timer
import pandas as pd
import numpy as np
from experiments import setup
from source import classifiers
from source import metrics
from source import util
from experiments.methods import svm
from experiments.methods import proposed_gmm_core_extraction
from experiments.methods import improved_intersection
from experiments.methods import compose
from experiments.methods import raul_classifier
from sklearn.grid_search import GridSearchCV
#from hpsklearn import HyperoptEstimator, any_classifier
#from hyperopt import tpe
'''
from experiments.methods import compose2
from experiments.methods import compose3
from experiments.methods import intersection
'''

def main():
    is_windows = sys.platform.startswith('win')
    sep = '\\'
    
    if is_windows == False:
        sep = '/'

    path = os.getcwd()+sep+'experiments'+sep+'data'+sep
    
    #loading a dataset
    allDataSets = [setup.load2CDT, setup.loadCHT, setup.load2CDT, setup.load2CHT, setup.loadUG_2C_2D, setup.loadUG_2C_3D, setup.loadUG_2C_5D, setup.loadMG_2C_2D, setup.loadFG_2C_2D, setup.loadGEARS_2C_2D, setup.load4CR, setup.load4CE1CF, setup.loadCheckerBoard]
    sizes=[200]
    batches=[79]
    #for d in range(len(allDataSets)):
    dataValues, dataLabels, databaseName = allDataSets[0](path, sep)
    print(len(dataValues))
    raul = raul_classifier.raulClassifier()
    #testing grid search
    #0.95, 0.9, 0.85, 0.8, 0.75, 0.7, 0.65
    tuned_params = {"excludingPercentage" : [0.95], "clfName":['cl'], "sizeOfBatch":[sizes[0]], "batches":[batches[0]]}
    gs = GridSearchCV(raul, tuned_params)
    gs.fit(dataValues, dataLabels)
    output = '{} -- Best Score: {}, achieved with following parameters: {}.'.format(databaseName,gs.best_score_,gs.best_params_)
    f = open('output'+sep+'gridsearch_selection.txt', 'a')
    f.write(output)
    f.close()
    
if __name__ == "__main__":
    main()


C:\Users\raul\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\Users\raul\Anaconda3\lib\site-packages\sklearn\grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


15999
0
[[ 18.693   13.545 ]
 [ 16.814   14.45  ]
 [ 13.929   14.891 ]
 [ 16.335   17.132 ]
 [ 16.269   17.012 ]
 [ 13.981   17.836 ]
 [ 10.643   12.14  ]
 [ 17.366   18.089 ]
 [ 13.444   11.009 ]
 [ 18.099   17.443 ]
 [ 12.159   12.634 ]
 [ 17.217   19.317 ]
 [ 19.068   17.136 ]
 [ 15.772   12.019 ]
 [ 17.485   12.094 ]
 [ 11.635   16.026 ]
 [ 16.046   18.279 ]
 [ 16.206   18.334 ]
 [ 18.749   17.465 ]
 [ 11.862   15.079 ]
 [ 10.336   12.851 ]
 [ 18.562   16.922 ]
 [ 10.682   13.957 ]
 [ 13.312   14.723 ]
 [ 12.18    16.516 ]
 [ 12.984   13.567 ]
 [ 15.849   17.617 ]
 [ 14.463   14.847 ]
 [ 18.42    12.981 ]
 [ 11.781   11.289 ]
 [ 14.481   13.14  ]
 [ 16.169   15.645 ]
 [ 18.636   14.843 ]
 [ 17.37    15.581 ]
 [ 18.565   16.837 ]
 [ 11.653   11.924 ]
 [ 14.394   13.072 ]
 [  8.9146  11.564 ]
 [ 18.337   17.319 ]
 [ 17.078   18.402 ]
 [ 19.213   15.848 ]
 [ 17.444   17.131 ]
 [ 15.821   15.384 ]
 [ 17.394   16.253 ]
 [ 16.086   16.048 ]
 [ 17.622   18.525 ]
 [ 10.649   14.643 ]
 [ 10

2
[[ 12.814  15.943]
 [ 19.948  16.942]
 [ 16.95   19.803]
 [ 15.587  14.209]
 [ 16.223  16.445]
 [ 17.433  17.905]
 [ 18.423  16.951]
 [ 17.826  20.135]
 [ 17.336  17.601]
 [ 15.357  17.023]
 [ 18.123  19.325]
 [ 18.568  19.205]
 [ 17.189  18.9  ]
 [ 19.19   19.193]
 [ 17.656  17.463]
 [ 16.194  13.239]
 [ 17.638  18.683]
 [ 12.413  16.031]
 [ 14.489  13.062]
 [ 18.678  18.025]
 [ 12.64   12.505]
 [ 20.892  18.005]
 [ 13.302  12.026]
 [ 12.994  11.141]
 [ 16.022  16.351]
 [ 14.262  12.133]
 [ 17.844  19.475]
 [ 13.384  12.934]
 [ 15.507  16.947]
 [ 17.604  19.552]
 [ 17.908  19.683]
 [ 18.808  17.64 ]
 [ 14.898  16.046]
 [ 17.098  17.692]
 [ 10.737  15.849]
 [ 17.421  15.816]
 [ 15.173  12.933]
 [ 15.578  15.009]
 [ 16.495  20.855]
 [ 17.417  18.919]
 [ 13.44   11.1  ]
 [ 16.036  20.648]
 [ 13.636  17.022]
 [ 18.893  18.069]
 [ 16.027  14.492]
 [ 15.201  13.879]
 [ 17.261  15.468]
 [ 16.919  17.485]
 [ 13.701  17.078]
 [ 18.252  19.948]
 [ 16.611  19.075]
 [ 16.942  17.47 ]
 [ 15.899 

5
[[ 18.843  16.646]
 [ 13.887  18.891]
 [ 18.086  18.988]
 [ 15.81   17.246]
 [ 16.589  14.161]
 [ 19.214  20.691]
 [ 15.939  16.252]
 [ 16.537  18.362]
 [ 14.044  15.291]
 [ 20.328  19.767]
 [ 16.712  18.171]
 [ 17.79   14.988]
 [ 15.072  15.379]
 [ 17.355  18.638]
 [ 18.109  19.211]
 [ 15.66   14.249]
 [ 19.311  20.003]
 [ 17.785  16.125]
 [ 19.159  19.777]
 [ 15.137  16.869]
 [ 16.137  11.557]
 [ 17.586  19.318]
 [ 12.816  16.829]
 [ 13.466  14.528]
 [ 16.611  14.812]
 [ 16.57   20.13 ]
 [ 13.637  15.424]
 [ 17.916  16.313]
 [ 18.426  18.72 ]
 [ 14.195  13.614]
 [ 16.238  21.516]
 [ 19.945  18.309]
 [ 19.656  18.791]
 [ 13.04   17.892]
 [ 19.941  18.919]
 [ 20.513  19.096]
 [ 14.356  16.98 ]
 [ 15.661  15.309]
 [ 15.759  13.189]
 [ 20.391  19.878]
 [ 17.008  14.56 ]
 [ 14.661  16.043]
 [ 16.606  12.994]
 [ 18.663  17.133]
 [ 14.357  14.766]
 [ 17.667  15.244]
 [ 16.532  10.519]
 [ 16.102  15.179]
 [ 18.127  16.945]
 [ 13.891  16.772]
 [ 14.328  16.838]
 [ 20.049  17.099]
 [ 17.721 

8
[[ 18.398  19.284]
 [ 18.822  17.517]
 [ 21.877  22.857]
 [ 14.282  14.522]
 [ 22.161  19.964]
 [ 20.307  21.166]
 [ 16.528  17.93 ]
 [ 20.663  20.332]
 [ 23.171  20.027]
 [ 18.996  17.674]
 [ 16.115  17.556]
 [ 17.91   17.683]
 [ 19.255  21.406]
 [ 19.366  20.228]
 [ 17.998  19.445]
 [ 23.141  20.604]
 [ 18.185  16.973]
 [ 13.453  18.228]
 [ 20.276  18.785]
 [ 15.982  18.846]
 [ 21.499  21.913]
 [ 19.403  21.861]
 [ 18.334  16.151]
 [ 19.115  20.679]
 [ 17.824  18.796]
 [ 18.443  17.416]
 [ 14.507  17.641]
 [ 22.41   20.544]
 [ 22.557  19.597]
 [ 17.382  16.276]
 [ 19.67   20.578]
 [ 23.134  21.118]
 [ 21.245  21.581]
 [ 18.948  20.257]
 [ 18.187  15.994]
 [ 18.596  18.021]
 [ 17.521  13.812]
 [ 16.14   15.713]
 [ 21.632  19.899]
 [ 17.622  16.244]
 [ 17.669  15.518]
 [ 23.255  21.005]
 [ 20.43   17.047]
 [ 14.392  15.571]
 [ 15.874  17.084]
 [ 21.718  20.61 ]
 [ 17.218  15.777]
 [ 14.093  17.111]
 [ 15.938  15.624]
 [ 16.387  18.032]
 [ 21.625  20.158]
 [ 16.55   16.807]
 [ 21.352 

11
[[ 16.821  19.7  ]
 [ 19.562  23.047]
 [ 16.276  19.631]
 [ 23.509  23.267]
 [ 23.328  23.942]
 [ 18.081  19.045]
 [ 23.155  23.286]
 [ 25.866  22.469]
 [ 23.733  22.792]
 [ 17.942  14.998]
 [ 19.061  18.696]
 [ 20.888  23.57 ]
 [ 18.887  16.107]
 [ 22.252  19.014]
 [ 22.153  19.802]
 [ 23.53   23.938]
 [ 22.182  24.705]
 [ 16.123  14.55 ]
 [ 21.685  23.966]
 [ 26.482  19.719]
 [ 19.409  21.365]
 [ 20.821  20.631]
 [ 20.772  23.646]
 [ 20.879  22.016]
 [ 22.702  24.17 ]
 [ 21.526  20.584]
 [ 21.287  22.525]
 [ 18.501  14.751]
 [ 17.822  17.307]
 [ 17.582  19.713]
 [ 18.305  21.674]
 [ 19.082  17.405]
 [ 19.418  16.39 ]
 [ 19.215  19.099]
 [ 21.289  24.539]
 [ 19.418  17.673]
 [ 20.732  21.222]
 [ 17.608  16.275]
 [ 16.352  18.732]
 [ 25.537  21.807]
 [ 20.06   18.149]
 [ 20.786  16.65 ]
 [ 20.818  22.898]
 [ 21.329  23.816]
 [ 22.588  21.787]
 [ 20.206  22.513]
 [ 15.457  17.248]
 [ 15.904  17.764]
 [ 16.714  16.889]
 [ 24.557  22.111]
 [ 17.067  16.67 ]
 [ 14.172  20.02 ]
 [ 22.966

14
[[ 23.741  22.307]
 [ 19.976  19.778]
 [ 20.504  18.992]
 [ 23.541  26.611]
 [ 23.248  23.142]
 [ 18.84   21.213]
 [ 17.985  17.825]
 [ 23.376  24.601]
 [ 24.161  25.557]
 [ 26.962  24.198]
 [ 20.688  22.032]
 [ 23.724  28.291]
 [ 26.359  24.284]
 [ 23.426  25.097]
 [ 24.568  22.941]
 [ 21.779  20.024]
 [ 24.694  22.86 ]
 [ 23.367  21.377]
 [ 22.81   24.1  ]
 [ 25.111  25.157]
 [ 19.736  19.782]
 [ 23.617  25.141]
 [ 21.697  18.513]
 [ 23.334  22.509]
 [ 20.592  19.492]
 [ 26.051  23.051]
 [ 26.484  23.469]
 [ 20.693  20.242]
 [ 20.398  20.711]
 [ 19.499  20.332]
 [ 22.428  18.835]
 [ 19.308  19.997]
 [ 20.456  19.783]
 [ 21.107  21.512]
 [ 19.711  21.502]
 [ 24.295  23.782]
 [ 25.312  21.625]
 [ 19.478  18.889]
 [ 20.931  21.756]
 [ 21.061  21.624]
 [ 26.107  23.165]
 [ 20.885  17.127]
 [ 21.612  18.934]
 [ 26.399  24.372]
 [ 25.126  25.585]
 [ 20.668  18.958]
 [ 22.721  23.782]
 [ 17.506  20.071]
 [ 24.48   26.016]
 [ 19.166  21.265]
 [ 22.547  19.209]
 [ 24.735  23.854]
 [ 23.982

17
[[ 17.786  18.956]
 [ 24.388  22.566]
 [ 23.987  22.785]
 [ 20.972  17.934]
 [ 22.992  19.549]
 [ 22.741  22.27 ]
 [ 19.095  18.128]
 [ 17.143  18.285]
 [ 23.695  25.035]
 [ 16.278  19.304]
 [ 19.494  20.014]
 [ 17.247  20.109]
 [ 23.424  22.192]
 [ 22.949  21.048]
 [ 20.463  17.329]
 [ 17.81   17.035]
 [ 26.309  24.518]
 [ 22.069  21.925]
 [ 18.113  18.791]
 [ 19.653  19.04 ]
 [ 25.828  23.159]
 [ 20.22   24.696]
 [ 23.055  25.012]
 [ 21.988  19.249]
 [ 16.995  19.215]
 [ 21.627  25.072]
 [ 24.694  22.129]
 [ 25.163  23.269]
 [ 22.047  19.498]
 [ 17.756  21.655]
 [ 19.171  17.204]
 [ 21.817  21.795]
 [ 22.19   19.726]
 [ 25.278  18.677]
 [ 17.536  18.513]
 [ 18.641  20.052]
 [ 17.537  20.113]
 [ 17.791  18.236]
 [ 18.368  17.968]
 [ 24.346  20.446]
 [ 22.211  21.071]
 [ 23.16   21.251]
 [ 23.369  22.397]
 [ 20.595  20.148]
 [ 20.061  18.759]
 [ 17.351  17.66 ]
 [ 21.148  22.051]
 [ 19.992  21.55 ]
 [ 22.283  23.701]
 [ 15.264  21.536]
 [ 22.267  20.891]
 [ 19.027  21.223]
 [ 17.123

20
[[ 18.551  18.757]
 [ 20.075  20.142]
 [ 17.289  16.854]
 [ 16.658  13.713]
 [ 16.146  18.565]
 [ 18.939  22.636]
 [ 15.195  17.87 ]
 [ 18.668  15.291]
 [ 17.837  17.01 ]
 [ 18.334  15.827]
 [ 19.652  18.033]
 [ 14.178  17.939]
 [ 17.288  19.594]
 [ 17.347  13.814]
 [ 18.35   15.556]
 [ 20.507  21.638]
 [ 19.635  20.28 ]
 [ 15.167  15.702]
 [ 24.392  21.578]
 [ 14.276  17.249]
 [ 15.848  16.529]
 [ 17.83   15.35 ]
 [ 18.474  13.112]
 [ 17.245  18.133]
 [ 17.226  16.325]
 [ 16.781  17.877]
 [ 20.739  22.116]
 [ 22.387  18.23 ]
 [ 14.509  15.065]
 [ 15.656  18.64 ]
 [ 22.329  20.903]
 [ 16.726  18.033]
 [ 21.18   21.264]
 [ 19.691  21.817]
 [ 17.356  15.385]
 [ 16.767  18.679]
 [ 22.222  19.572]
 [ 21.589  21.587]
 [ 18.826  17.517]
 [ 18.784  17.022]
 [ 21.38   21.51 ]
 [ 16.426  18.952]
 [ 21.618  22.042]
 [ 18.667  21.793]
 [ 24.327  19.086]
 [ 16.623  15.667]
 [ 17.828  16.851]
 [ 13.921  15.765]
 [ 17.58   15.121]
 [ 15.488  19.155]
 [ 19.048  16.047]
 [ 18.464  18.358]
 [ 22.31 

23
[[ 16.467  16.28 ]
 [ 18.75   20.269]
 [ 16.237  15.824]
 [ 23.68   21.358]
 [ 13.536  15.785]
 [ 21.051  19.456]
 [ 17.66   16.06 ]
 [ 19.113  19.019]
 [ 17.632  15.912]
 [ 16.718  15.569]
 [ 15.064  16.301]
 [ 21.537  19.733]
 [ 15.669  17.232]
 [ 16.055  15.776]
 [ 14.848  15.756]
 [ 19.869  18.584]
 [ 17.491  19.539]
 [ 15.343  16.183]
 [ 16.807  14.65 ]
 [ 18.504  21.223]
 [ 21.083  14.95 ]
 [ 19.813  20.404]
 [ 21.006  20.62 ]
 [ 15.612  15.287]
 [ 18.929  19.447]
 [ 19.724  19.502]
 [ 20.922  20.561]
 [ 17.365  14.418]
 [ 15.132  14.52 ]
 [ 20.063  18.817]
 [ 21.853  19.582]
 [ 15.018  17.386]
 [ 21.706  19.56 ]
 [ 20.342  20.558]
 [ 16.382  15.051]
 [ 19.781  19.514]
 [ 19.134  20.79 ]
 [ 15.942  16.202]
 [ 18.586  20.357]
 [ 17.693  18.864]
 [ 20.227  21.694]
 [ 14.052  16.29 ]
 [ 15.662  13.725]
 [ 17.604  16.26 ]
 [ 15.764  16.94 ]
 [ 11.68   13.473]
 [ 16.919  17.142]
 [ 15.752  16.157]
 [ 17.319  18.167]
 [ 19.282  18.286]
 [ 20.73   18.032]
 [ 15.816  13.924]
 [ 19.719

26
[[ 14.948   13.728 ]
 [ 15.465   12.382 ]
 [ 18.836   17.686 ]
 [ 13.841   13.957 ]
 [ 15.982   13.497 ]
 [ 19.33    19.61  ]
 [ 16.246   17.016 ]
 [ 10.999   10.467 ]
 [ 15.734   11.972 ]
 [ 13.432   13.738 ]
 [ 14.164   14.417 ]
 [ 17.247   15.508 ]
 [ 15.442   14.935 ]
 [ 14.017   14.122 ]
 [ 14.601   15.114 ]
 [ 20.806   21.392 ]
 [ 13.263   10.989 ]
 [ 14.285   15.822 ]
 [ 19.002   17.49  ]
 [ 17.955   15.563 ]
 [ 11.902   12.989 ]
 [ 12.482   11.741 ]
 [ 10.9     16.528 ]
 [ 17.348   18.231 ]
 [ 13.141   15.132 ]
 [ 19.262   18.162 ]
 [ 16.601   17.031 ]
 [ 17.024   19.558 ]
 [ 16.438   20.014 ]
 [ 13.44    15.847 ]
 [ 18.568   18.099 ]
 [ 13.643   11.977 ]
 [ 14.315   14.099 ]
 [ 12.576   12.903 ]
 [ 17.235   17.695 ]
 [ 15.231   13.588 ]
 [ 15.146   13.199 ]
 [ 12.386   13.532 ]
 [ 16.8     19.021 ]
 [ 13.972   14.875 ]
 [ 18.18    17.725 ]
 [ 20.078   18.785 ]
 [ 14.981   11.935 ]
 [ 14.874   18.39  ]
 [ 20.596   20.107 ]
 [ 15.342   14.568 ]
 [ 16.406   16.962 ]
 [ 14.096 

29
[[ 15.165   17.329 ]
 [ 16.443   15.205 ]
 [ 14.809   12.802 ]
 [ 14.171   13.76  ]
 [ 15.613   17.4   ]
 [ 15.259   15.122 ]
 [ 14.452   14.343 ]
 [ 18.954   16.664 ]
 [ 18.931   17.798 ]
 [ 19.354   18.113 ]
 [ 16.582   17.872 ]
 [ 16.406   13.012 ]
 [ 19.272   18.671 ]
 [ 13.891   11.867 ]
 [ 13.146   13.048 ]
 [ 17.509   17.438 ]
 [ 15.472   13.532 ]
 [ 14.525   12.763 ]
 [ 15.505   16.992 ]
 [ 17.635   15.676 ]
 [ 16.647   17.484 ]
 [ 17.702   15.058 ]
 [ 16.614   17.409 ]
 [ 13.247   14.83  ]
 [ 17.586   17.826 ]
 [ 12.96     9.5499]
 [ 16.469   14.158 ]
 [ 13.974   16.04  ]
 [ 14.139   10.914 ]
 [ 12.512   12.296 ]
 [ 11.817   13.611 ]
 [ 14.657   16.224 ]
 [ 15.525   19.189 ]
 [ 14.893   17.553 ]
 [ 20.377   17.122 ]
 [ 16.775   15.519 ]
 [ 16.76    17.63  ]
 [ 11.438   13.216 ]
 [ 16.574   15.681 ]
 [ 14.607   15.402 ]
 [ 13.139   15.078 ]
 [ 16.646   17.135 ]
 [ 18.837   18.144 ]
 [ 16.672   18.117 ]
 [ 16.717   16.576 ]
 [ 14.15    12.259 ]
 [ 14.811   13.11  ]
 [ 16.691 

32
[[ 10.941   11.629 ]
 [  8.4266   7.9353]
 [ 13.892   14.999 ]
 [ 12.414   10.206 ]
 [ 15.567   13.083 ]
 [ 12.832   11.863 ]
 [ 15.417   15.517 ]
 [  7.3587  11.846 ]
 [  9.6404   9.2149]
 [ 10.557    8.6976]
 [ 12.937   15.182 ]
 [ 17.332   16.628 ]
 [ 10.044   13.208 ]
 [ 11.692   16.406 ]
 [ 16.947   13.243 ]
 [ 15.975   12.921 ]
 [ 11.752   12.168 ]
 [ 13.094   10.736 ]
 [  9.4034  12.281 ]
 [  8.6936   9.6518]
 [  9.0054  12.131 ]
 [ 16.064   13.908 ]
 [ 13.273   16.118 ]
 [ 11.944   11.678 ]
 [ 11.452   10.741 ]
 [ 12.126   12.428 ]
 [ 17.394   13.539 ]
 [  9.6018  12.947 ]
 [ 14.884   18.413 ]
 [ 14.105   16.39  ]
 [ 13.922   16.031 ]
 [ 13.773   11.378 ]
 [ 12.632   10.308 ]
 [ 13.489   15.619 ]
 [ 14.901   14.913 ]
 [ 10.108   11.957 ]
 [ 12.782   10.267 ]
 [  9.372   10.968 ]
 [ 14.452   16.582 ]
 [ 13.11    12.808 ]
 [  9.3547   9.9978]
 [ 12.359   11.403 ]
 [ 12.874   14.558 ]
 [ 15.957   15.62  ]
 [ 11.965   13.971 ]
 [ 10.162   11.592 ]
 [  8.7646  10.959 ]
 [ 14.584 

[[ 10.546    9.5949]
 [ 11.052    9.8372]
 [ 13.801    9.2447]
 [ 13.765   15.174 ]
 [  9.3551  10.671 ]
 [  7.598   11.153 ]
 [  7.9142   9.793 ]
 [ 10.478    9.4389]
 [ 14.635   13.524 ]
 [ 10.268    9.9788]
 [ 11.862   13.366 ]
 [ 11.499   11.945 ]
 [ 11.737    9.5272]
 [ 12.947   14.023 ]
 [ 11.18     8.7023]
 [ 12.034   13.651 ]
 [ 15.492   13.857 ]
 [ 13.148   15.513 ]
 [ 12.124    9.7225]
 [ 14.111   13.934 ]
 [ 12.24    10.147 ]
 [ 14.376   16.024 ]
 [ 15.258   15.271 ]
 [ 14.15    13.645 ]
 [ 17.005   13.656 ]
 [ 10.605   11.034 ]
 [ 14.854   13.105 ]
 [ 10.734    9.2287]
 [ 14.778   14.026 ]
 [ 13.479    8.6891]
 [  9.8751  10.16  ]
 [ 13.663   11.356 ]
 [  8.9272   7.9497]
 [ 14.685   11.657 ]
 [ 11.401   12.133 ]
 [  9.0642  12.588 ]
 [  9.8787  10.013 ]
 [  9.55     8.9136]
 [ 15.71    17.033 ]
 [ 12.251   13.832 ]
 [  7.9774   9.0087]
 [ 13.602   12.327 ]
 [  8.8683   9.8218]
 [ 12.968   14.41  ]
 [ 14.737   17.188 ]
 [ 10.22     9.3281]
 [ 15.502   12.648 ]
 [ 11.53    1

37
[[  7.8903  10.305 ]
 [  7.5948   5.4133]
 [  7.4236   7.7739]
 [  9.4073   8.341 ]
 [ 13.135   12.656 ]
 [ 12.616   14.009 ]
 [  8.3772   8.9825]
 [  9.0897   9.2842]
 [  9.2332   9.4973]
 [ 10.33     8.5264]
 [  8.4273   6.1596]
 [  9.8449  13.802 ]
 [  8.7519   8.8709]
 [ 11.221   11.513 ]
 [ 11.13    10.607 ]
 [  9.3372   8.9283]
 [  8.7416   9.1247]
 [ 13.551   12.409 ]
 [  9.3031  10.871 ]
 [  7.7888   9.5301]
 [ 12.49    11.929 ]
 [  6.8821   8.8765]
 [ 13.291    9.8018]
 [ 11.979   13.946 ]
 [ 10.257    7.7391]
 [ 10.781   10.371 ]
 [ 10.589   13.479 ]
 [ 11.337    9.5485]
 [  8.6674   8.1592]
 [  9.7446  10.187 ]
 [ 12.489   13.811 ]
 [ 10.727    4.3495]
 [ 13.815   12.53  ]
 [ 13.716   13.569 ]
 [ 12.135   10.373 ]
 [  7.1116  10.11  ]
 [  7.7358  11.909 ]
 [ 11.94    13.882 ]
 [ 12.436    8.6144]
 [  9.0772   8.1943]
 [  8.5283  11.847 ]
 [  9.8786  10.281 ]
 [ 11.128    9.4358]
 [ 15.691   13.434 ]
 [ 11.348    6.881 ]
 [  9.6625  10.359 ]
 [  8.6218   9.259 ]
 [ 15.474 

40
[[ 12.073   11.754 ]
 [ 10.49    10.421 ]
 [ 11.053    8.6343]
 [  6.7768   6.7209]
 [ 10.37    12.101 ]
 [  6.4889   6.7144]
 [ 11.231    9.5147]
 [  8.1883   7.3418]
 [  7.5667   7.4476]
 [  9.747   11.655 ]
 [  7.2804   6.6473]
 [ 11.726   11.692 ]
 [  9.9483  11.903 ]
 [ 13.144    7.5379]
 [  6.0004   7.4105]
 [  9.8373   9.7813]
 [  8.4383   5.1008]
 [ 10.702   12.855 ]
 [ 13.212    8.6377]
 [  7.1525   7.2468]
 [  9.3601   5.169 ]
 [ 11.37    12.66  ]
 [ 10.264    9.4255]
 [  9.7687   5.7669]
 [  6.6506   7.1808]
 [ 10.669    9.6142]
 [  7.3675   4.3581]
 [  6.8164  11.113 ]
 [  5.4112  11.179 ]
 [  8.341    3.7289]
 [  6.969    8.4807]
 [ 12.705   12.904 ]
 [  4.6649   6.1093]
 [  7.7217   6.8416]
 [  7.0971   8.3435]
 [  9.3428   9.3178]
 [  7.2559   6.8711]
 [  9.4508   4.1782]
 [  9.9748   9.955 ]
 [ 10.401   10.596 ]
 [  5.843    5.6842]
 [ 10.367   10.585 ]
 [ 12.847    7.6797]
 [  7.879    9.9072]
 [  7.6989   8.7489]
 [ 10.592   11.444 ]
 [  8.442   12.443 ]
 [ 12.194 

43
[[  7.2103   5.2603]
 [  6.1682   8.052 ]
 [  8.1139   8.2474]
 [ 12.64    11.467 ]
 [  7.6681   5.8509]
 [ 12.701    9.2337]
 [  7.356    6.0491]
 [  9.0605  10.198 ]
 [  8.5294   8.2632]
 [  5.5476   2.2425]
 [  8.0385   1.7658]
 [ 12.505    8.8921]
 [ 10.296    8.4763]
 [  9.4342   8.8743]
 [  6.2634   4.6824]
 [  8.2446  10.634 ]
 [  9.3296   8.6801]
 [  6.3227   6.9982]
 [ 10.267    8.6012]
 [  5.1863   4.7247]
 [  6.1267   8.6112]
 [ 11.884    9.8966]
 [  3.5635   3.4472]
 [  9.948    7.2438]
 [  5.5975   7.9618]
 [  2.4648   7.1399]
 [  9.1991  10.364 ]
 [  8.7186   9.2232]
 [  5.589    6.5912]
 [  6.2071   4.9714]
 [ 11.864   12.033 ]
 [  5.219    7.8658]
 [ 11.506   12.137 ]
 [ 11.476   11.698 ]
 [  8.2965   4.4486]
 [  8.992    9.2146]
 [  8.5109  11.238 ]
 [ 10.595   12.913 ]
 [  7.6474   5.011 ]
 [ 11.959    8.6853]
 [  7.0753   4.1593]
 [  9.2328  10.161 ]
 [ 10.739   11.171 ]
 [  9.4816  11.527 ]
 [  8.1633  10.701 ]
 [  6.7401   4.9836]
 [  4.2539   6.8794]
 [  5.589 

46
[[  7.1198    10.212   ]
 [  5.3987     9.3187  ]
 [  7.4383     8.6151  ]
 [  5.4293     9.0721  ]
 [  4.6639     3.1748  ]
 [  3.2124     4.3172  ]
 [  5.5423     8.4193  ]
 [ 10.643      5.5988  ]
 [  7.3778     9.2407  ]
 [  2.8838     4.0117  ]
 [  7.2548     6.1359  ]
 [  6.9157     6.7298  ]
 [  3.0289     4.4826  ]
 [  6.4895     9.9021  ]
 [  9.2531     5.7092  ]
 [  2.2234     3.9597  ]
 [  5.915      6.849   ]
 [  3.8487     4.6831  ]
 [  7.3869     3.467   ]
 [  3.5063     2.0923  ]
 [  7.867      8.4072  ]
 [  3.3565     6.1374  ]
 [  9.2247     8.3953  ]
 [  5.9825     7.3253  ]
 [  5.446      3.5195  ]
 [  8.2777     6.3205  ]
 [  8.9299     6.98    ]
 [  0.97825    4.6601  ]
 [  7.0327     7.951   ]
 [  7.4195     6.8975  ]
 [  8.488     10.109   ]
 [  2.6991     2.1783  ]
 [  5.8788     1.9388  ]
 [  3.7429     2.2084  ]
 [  1.8965     7.0501  ]
 [  9.4501     9.7557  ]
 [ 11.162      8.5988  ]
 [  5.1009     3.5749  ]
 [  4.7985     2.3853  ]
 [  5.9762     5.3344 

49
[[  5.0656     2.0329  ]
 [  2.483      1.6791  ]
 [  7.7503     7.9945  ]
 [  5.0169     3.2868  ]
 [  6.4719     7.7233  ]
 [  1.9836     5.3717  ]
 [  4.8552     3.8975  ]
 [  1.2962     1.7954  ]
 [  6.7451     5.8641  ]
 [  0.72361    3.7895  ]
 [  4.4927     0.29151 ]
 [  5.3978     7.7653  ]
 [  1.5454     1.4076  ]
 [  0.1668     3.0251  ]
 [  2.606      3.7091  ]
 [  3.8616     1.7548  ]
 [  8.8796     7.819   ]
 [  7.5436     6.4683  ]
 [  2.2398     3.5141  ]
 [  6.004      4.3767  ]
 [  7.6429     4.5596  ]
 [  5.1831     6.633   ]
 [  4.3904     0.694   ]
 [  1.6502     1.9252  ]
 [  9.3109     5.8883  ]
 [  4.9147     6.6845  ]
 [  7.5712     6.2765  ]
 [  6.2208     5.913   ]
 [  5.3194     6.807   ]
 [  2.6964     1.3598  ]
 [  2.9263     3.6275  ]
 [  2.7136     3.6447  ]
 [  7.107      8.6029  ]
 [  8.6004     6.4816  ]
 [  6.3807     6.6078  ]
 [  7.5946     6.2352  ]
 [  1.9139     4.3193  ]
 [  7.1711     4.3681  ]
 [ 11.013      7.8952  ]
 [  6.2182     7.574  

52
[[ 2.6199    0.63292 ]
 [ 5.3864    4.8757  ]
 [ 8.1861    5.0507  ]
 [-1.2358    1.6815  ]
 [ 1.7225    2.5668  ]
 [ 3.4595    3.0961  ]
 [ 1.3115   -0.08622 ]
 [ 2.1132    6.5321  ]
 [ 4.183     5.8161  ]
 [ 2.539     5.5749  ]
 [ 1.8119    0.79714 ]
 [-0.25481   0.1816  ]
 [-0.63435  -0.71794 ]
 [ 2.5255    2.1851  ]
 [ 5.9117    3.9072  ]
 [ 8.2201    3.9329  ]
 [ 4.3978    8.0308  ]
 [ 5.8879    7.8649  ]
 [ 0.14126   1.3546  ]
 [ 2.1055    4.4426  ]
 [ 6.2314    7.1293  ]
 [ 6.5323    1.9428  ]
 [ 5.2559    4.4934  ]
 [ 4.6977    4.2978  ]
 [ 6.6418    4.9724  ]
 [-0.69581   0.18126 ]
 [ 4.1604    4.3538  ]
 [ 3.5673    6.2276  ]
 [-0.036407  1.7244  ]
 [ 5.5886    3.4042  ]
 [ 6.6032    1.8165  ]
 [ 7.9809    3.6251  ]
 [ 4.961     5.7739  ]
 [ 0.094033  3.9123  ]
 [ 2.1086    2.3945  ]
 [ 4.4366    5.7773  ]
 [ 3.6818    3.8655  ]
 [ 5.5853    2.4184  ]
 [ 6.6892    5.1217  ]
 [ 4.8009    5.4774  ]
 [ 2.6427    4.4413  ]
 [ 2.4984    3.7316  ]
 [ 8.323     6.0912  ]
 [ 2.825

ValueError: Found array with 0 sample(s) (shape=(0, 2)) while a minimum of 1 is required.